Updated CheckOut Page
kbmDotLog/benshada-frontend pull request #48
Opened 2020-09-14 20:27 UTC by Oyinbayode

2020-09-14 22:59 UTC, amjedidiah requested changes
Nice work @Oyinbayode 
You were also able to replicate the mobile responsiveness
Welldone

### Some observations
1. The order summary isn't visible on smaller screens
2. You implemented just one screen out of the 4 screens

2020-09-16 13:53 UTC, Oyinbayode commented
OOOh, My Bad
I will work on the other 3 and also the order summary too

2020-09-21 23:16 UTC, amjedidiah requested changes
Nice @Oyinbayode 
I particularly like how you implemented the country selection

2 pages down, 1 last page to go(refer to the last 2 images).
Keep up the good work

2020-09-23 21:14 UTC, amjedidiah approved these changes

2020-09-23 21:14 UTC, merged